#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: xubuntu-vm
    username: irinelko
    password: "$1$7RCQsH9j$fxxlSR9SECru3MzYTy3j1/"
  keyboard:
    layout: us
  locale: en_US.UTF-8
  timezone: UTC
  ssh:
    install-server: true
    allow-pw: true
  network:
    ethernets:
      ens33:
        dhcp4: true
    version: 2
  storage:
    layout:
      name: lvm
  packages:
    - xubuntu-desktop
    - xfce4-terminal
    - xrdp
    - net-tools
    - curl
    - wget
    - git
    - docker.io  # Add Docker package here
  user-data:
    disable_root: false
  late-commands:
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get upgrade -y
    # XRDP with H.264 support
    - curtin in-target -- apt purge xrdp xorgxrdp
    - curtin in-target -- apt-add-repository ppa:saxl/xrdp-egfx
    - curtin in-target -- apt install xrdp-egfx xorgxrdp-egfx
    - curtin in-target -- apt install pulseaudio-module-xrdp
    # Install Docker Compose
    - curtin in-target -- curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - curtin in-target -- chmod +x /usr/local/bin/docker-compose
    # Add user to Docker group
    - curtin in-target -- usermod -aG docker irinelko
    # Install Node.js
    - curtin in-target -- wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
    - curtin in-target -- nvm use 23
    # Disable screen lock
    - chroot /target su -c "gsettings set org.gnome.desktop.screensaver lock-enabled false" ubuntu
    - chroot /target su -c "gsettings set org.gnome.desktop.screensaver idle-activation-enabled false" ubuntu
    - chroot /target su -c "gsettings set org.gnome.desktop.session idle-delay 0" ubuntu
    - chroot /target su -c "gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false" ubuntu
    - chroot /target su -c "gsettings set org.gnome.desktop.lockdown disable-lock-screen true" ubuntu
