#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: xubuntu-vm
    username: irinelko
    password: "$1$7RCQsH9j$fxxlSR9SECru3MzYTy3j1/"
  keyboard:
    layout: us
  locale: en_US.UTF-8
  timezone: UTC
  ssh:
    install-server: true
    allow-pw: true
  network:
    ethernets:
      ens33:
        dhcp4: true
    version: 2
  storage:
    layout:
      name: lvm
  packages:
    - xubuntu-desktop
    - xfce4-terminal
    - xrdp
    - net-tools
    - curl
    - wget
    - git
  user-data:
    disable_root: false
  late-commands:
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get upgrade -y
    - curtin in-target -- apt purge xrdp xorgxrdp
    - curtin in-target -- apt-add-repository ppa:saxl/xrdp-egfx
    - curtin in-target -- apt install xrdp-egfx xorgxrdp-egfx
    - curtin in-target -- apt install pulseaudio-module-xrdp
    - curtin in-target -- wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
    - curtin in-target -- nvm use 23
